Enable AWS_BUCKET on aws/terraform commands.

diff --git a/iac/terraform/Makefile b/iac/terraform/Makefile
--- a/iac/terraform/Makefile
+++ b/iac/terraform/Makefile
@@ -2,23 +2,30 @@
 
 help:
 	@echo  '---------------------------------------------------------------------------'
-	@echo  ' This Makefile that provides a convenient interface to run helper scripts.'
+	@echo  '   Makefile that provides a convenient interface to run helper scripts'
 	@echo  '---------------------------------------------------------------------------'
 	@echo  ''
-	@echo  '"make" targets:'
+	@echo  "Override 'default' profile with env: 'AWS_PROFILE=<name> make <target>'"
 	@echo  ''
+	@echo  "'make' targets:"
 	@echo  '  help                  - Show this help'
 	@echo  '  create-state-bucket   - Create an encrypted, versioned, non-public S3'
 	@echo  '                          bucket for Terraform state'
-	@echo  '  destroy-state-bucket  - !!! Permanently destroy S3 state bucket !!!'
-	@echo  '  init                  - Run 'terraform init' using state bucket (default)'
+	@echo  '  init                  - Run 'terraform init' using remote state bucket'
 	@echo  '  plan                  - Run 'terraform plan' using selected workspace'
 	@echo  '  apply                 - Run 'terraform apply' using selected workspace'
 	@echo  '  delete-sage           - Delete SageMaker models/endpoints for cleanup'
 	@echo  ''
+	@echo  'CAREFUL: TARGET ACTIONS THAT CANNOT BE UNDONE!'
+	@echo  '  destroy-state-bucket  - !!! Permanently destroy S3 state bucket !!!'
+	@echo  '  clean                 - !!! Remove local terraform state files !!!'
+	@echo  ''
 
 # Default environment (e.g., dev, staging, prod)
 WORKSPACE ?= dev
+
+# AWS profile
+AWS_PROFILE ?= default
 
 # AWS region for the bucket (can override this as needed)
 AWS_REGION ?= us-east-2
@@ -29,23 +36,27 @@ RANDOM_SUFFIX := $(shell openssl rand -hex 4)
 # Construct the state bucket name, e.g., esm-partner-dev-364ac8fd
 STATE_BUCKET_NAME := esm-partner-$(WORKSPACE)-$(RANDOM_SUFFIX)
 
+# Terraform backend config file
+BACKEND_CONFIG ?= backend.config
+
 create-state-bucket-config:
 	# @sed -e "s/STATE_BUCKET/$(STATE_BUCKET_NAME)/g" -e "s/AWS_REGION/$(AWS_REGION)/g" state-bucket-template.yaml > state-bucket-config.yaml
 	@sed -e "s/WORKSPACE/$(WORKSPACE)/g" \
 	    -e "s/AWS_REGION/$(AWS_REGION)/g" \
-		-e "s/STATE_BUCKET_NAME/$(STATE_BUCKET_NAME)/g" backend-template.config > backend.config
+		-e "s/STATE_BUCKET_NAME/$(STATE_BUCKET_NAME)/g" backend-template.config > $(BACKEND_CONFIG)
 
 # Create an encrypted, versioned, non-public S3 bucket for Terraform state
 create-state-bucket: create-state-bucket-config
 	@echo "Creating state bucket: $(STATE_BUCKET_NAME)"
-	aws s3api create-bucket --bucket $(STATE_BUCKET_NAME) --region $(AWS_REGION) --create-bucket-configuration LocationConstraint=$(AWS_REGION)
+	aws --profile=$(AWS_PROFILE) s3api create-bucket --bucket $(STATE_BUCKET_NAME) --region $(AWS_REGION) --create-bucket-configuration LocationConstraint=$(AWS_REGION)
 	@echo "Enabling encryption on bucket: $(STATE_BUCKET_NAME)"
-	aws s3api put-bucket-encryption --bucket $(STATE_BUCKET_NAME) --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
+	aws --profile=$(AWS_PROFILE) s3api put-bucket-encryption --bucket $(STATE_BUCKET_NAME) --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
 	@echo "Enabling versioning on bucket: $(STATE_BUCKET_NAME)"
-	aws s3api put-bucket-versioning --bucket $(STATE_BUCKET_NAME) --versioning-configuration Status=Enabled
+	aws --profile=$(AWS_PROFILE) s3api put-bucket-versioning --bucket $(STATE_BUCKET_NAME) --versioning-configuration Status=Enabled
 	@echo "Blocking public access on bucket: $(STATE_BUCKET_NAME)"
-	aws s3api put-public-access-block --bucket $(STATE_BUCKET_NAME) --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
+	aws --profile=$(AWS_PROFILE) s3api put-public-access-block --bucket $(STATE_BUCKET_NAME) --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
 	@echo "Bucket $(STATE_BUCKET_NAME) created and configured."
+	aws --profile=$(AWS_PROFILE) s3 ls | grep $(STATE_BUCKET_NAME)
 
 # Destroy (delete) the state bucket. CAREFUL! This will permanently delete the bucket.
 destroy-state-bucket:
@@ -54,8 +65,8 @@ destroy-state-bucket:
 		exit 1; \
 	fi
 	@echo "Destroying state bucket..."
-	@# Extract the bucket name from backend.config
-	@BUCKET_NAME=`awk -F\" '/^bucket/ {print $$2}' backend.config 2>/dev/null`; \
+	@# Extract the bucket name from $(BACKEND_CONFIG)
+	@BUCKET_NAME=`awk -F\" '/^bucket/ {print $$2}' $(BACKEND_CONFIG) 2>/dev/null`; \
 	echo "Using bucket: $$BUCKET_NAME"; \
 	aws s3api delete-objects \
 		--bucket $$BUCKET_NAME \
@@ -63,27 +74,38 @@ destroy-state-bucket:
 			--bucket "$$BUCKET_NAME" \
 			--output=json \
 			--query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}'`"; \
-	aws s3 rb s3://$$BUCKET_NAME --force
+	aws s3 rb s3://$$BUCKET_NAME --force && \
+	rm -i $(BACKEND_CONFIG)
 
 # Existing targets for startup and Terraform operations
 
 init:
+	@echo "Initializing terraform and creating workspace $(WORKSPACE)"
 	terraform init -backend-config=backend.config
+	AWS_PROFILE=partner-prem-dev terraform workspace new dev 
 
 set-workspace:
-	terraform workspace select $(WORKSPACE)
+	AWS_PROFILE=$(AWS_PROFILE) terraform workspace select $(WORKSPACE)
 
 plan: set-workspace
-	terraform plan
+	env AWS_PROFILE=$(AWS_PROFILE) terraform plan
 
 apply: set-workspace
 	@echo "Deploying $(WORKSPACE)"
-	terraform apply
+	env AWS_PROFILE=$(AWS_PROFILE) terraform apply
 
 apply-ci:
 	@echo "Deploying $(WORKSPACE)"
-	terraform init -input=false -no-color
-	terraform apply -auto-approve
+	env AWS_PROFILE=$(AWS_PROFILE) terraform init -input=false -no-color
+	env AWS_PROFILE=$(AWS_PROFILE) terraform apply -auto-approve
+
+clean:
+	@if [ "$(WORKSPACE)" != "dev" ]; then \
+		echo "Error: clean can only be run in the 'dev' workspace, not in '$(WORKSPACE)'"; \
+		exit 1; \
+	fi
+	@echo "Removing local terraform state files..."
+	rm -R .terraform .terraform.lock.hcl
 
 # Delete SageMaker models/endpoints for cleanup
 delete-sage:
